.data
.pushsection .hyp.reloc, "a"
.global __hyp_section_.hyp.idmap.text
.word 0
.reloc 0, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xa68
.word 0
.reloc 4, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xa70
.global __hyp_section_.hyp.text
.word 0
.reloc 8, R_AARCH64_PREL32, __hyp_section_.hyp.text + 0xfe8
.word 0
.reloc 12, R_AARCH64_PREL32, __hyp_section_.hyp.text + 0xff0
.word 0
.reloc 16, R_AARCH64_PREL32, __hyp_section_.hyp.text + 0xff8
.global __hyp_section_.hyp.rodata
.word 0
.reloc 20, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a8
.word 0
.reloc 24, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b0
.word 0
.reloc 28, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b8
.word 0
.reloc 32, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c0
.word 0
.reloc 36, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c8
.word 0
.reloc 40, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d0
.word 0
.reloc 44, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d8
.word 0
.reloc 48, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e0
.word 0
.reloc 52, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e8
.word 0
.reloc 56, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f0
.word 0
.reloc 60, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f8
.word 0
.reloc 64, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x300
.word 0
.reloc 68, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x308
.word 0
.reloc 72, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x310
.word 0
.reloc 76, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x318
.word 0
.reloc 80, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x320
.word 0
.reloc 84, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x328
.word 0
.reloc 88, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x330
.word 0
.reloc 92, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x338
.word 0
.reloc 96, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x340
.popsection
